apiVersion: apps/v1
kind: Deployment
metadata:
  name: scala-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scala-app
  template:
    metadata:
      labels:
        app: scala-app
    spec:
      containers:
      - name: scala-app
        image: amarjanthe/scala-devsecops-app:1.0
        ports:
        - containerPort: 8080
