apiVersion: v1
kind: Service
metadata:
  name: scala-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: scala-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
